# Generated by Django 6.0.7 on 2026-07-27 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='عنوان متا')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='توضیحات متا')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og/', verbose_name='تصویر Open Graph')),
                ('canonical_url', models.URLField(blank=True, verbose_name='آدرس Canonical')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True, verbose_name='اسلاگ')),
                ('name', models.CharField(max_length=150, verbose_name='نام دسته\u200cبندی')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='آیکون')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/categories/', verbose_name='تصویر')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.productcategory', verbose_name='دسته\u200cبندی والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی محصول',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای محصولات',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='عنوان متا')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='توضیحات متا')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og/', verbose_name='تصویر Open Graph')),
                ('canonical_url', models.URLField(blank=True, verbose_name='آدرس Canonical')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True, verbose_name='اسلاگ')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده')], default='draft', max_length=10, verbose_name='وضعیت')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='توضیح کوتاه')),
                ('description', models.TextField(verbose_name='توضیحات کامل')),
                ('cover_image', models.ImageField(upload_to='products/covers/', verbose_name='تصویر شاخص')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='برند / سازنده')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='قیمت (تومان)')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='قیمت با تخفیف')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='موجودی انبار')),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='کد محصول (SKU)')),
                ('is_orderable', models.BooleanField(default=False, help_text='برای فاز فروشگاه', verbose_name='قابل سفارش آنلاین')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان فایل')),
                ('file', models.FileField(upload_to='products/downloads/', verbose_name='فایل')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'فایل دانلودی محصول',
                'verbose_name_plural': 'فایل\u200cهای دانلودی محصول',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='تصویر')),
                ('alt_text', models.CharField(blank=True, max_length=150, verbose_name='متن جایگزین (Alt)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'گالری تصاویر محصول',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('company_name', models.CharField(blank=True, max_length=150, verbose_name='نام شرکت')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد مورد نیاز')),
                ('message', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_read', models.BooleanField(default=False)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='products.product')),
            ],
            options={
                'verbose_name': 'استعلام قیمت محصول',
                'verbose_name_plural': 'استعلام\u200cهای قیمت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='عنوان مشخصه')),
                ('value', models.CharField(max_length=255, verbose_name='مقدار')),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'مشخصه فنی',
                'verbose_name_plural': 'مشخصات فنی',
                'ordering': ['order'],
            },
        ),
    ]
