# Generated by Django 6.0.7 on 2026-10-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_finalize_brand_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='default_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='مثلاً ۳۵ یعنی ۳۵٪ -- روی همه\u200cی محصولات این برند اعمال می\u200cشود مگر محصولی تخفیف اختصاصی داشته باشد', max_digits=5, verbose_name='درصد تخفیف پیش\u200cفرض برند'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percent_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='اگر پر شود، به\u200cجای تخفیف پیش\u200cفرض برند برای همین محصول استفاده می\u200cشود', max_digits=5, null=True, verbose_name='درصد تخفیف اختصاصی این محصول (اختیاری)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mpn',
            field=models.CharField(blank=True, db_index=True, help_text='کدی که خودِ سازنده/برند به این محصول داده (مثلاً روی کاتالوگ یا PDF قیمت)', max_length=100, verbose_name='کد سازنده (MPN)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='کد محصول داخلی (SKU)'),
        ),
    ]
