# Generated by Django 6.0.7 on 2026-10-09 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0100_unique_attribute_per_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filterableattribute',
            name='category',
        ),
        migrations.RenameIndex(
            model_name='attribute',
            new_name='products_at_data_ty_5af76c_idx',
            old_name='prod_attr_type_active_idx',
        ),
        migrations.RenameIndex(
            model_name='attributevalue',
            new_name='products_at_attribu_345de0_idx',
            old_name='prod_attr_val_norm_idx',
        ),
        migrations.RenameIndex(
            model_name='attributevalue',
            new_name='products_at_attribu_dff750_idx',
            old_name='prod_attr_val_usage_idx',
        ),
        migrations.RenameIndex(
            model_name='productattributevalue',
            new_name='products_pr_attribu_f70fb0_idx',
            old_name='prod_pav_attr_num_idx',
        ),
        migrations.RenameIndex(
            model_name='productattributevalue',
            new_name='products_pr_attribu_0b6e23_idx',
            old_name='prod_pav_attr_bool_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='products_pr_product_66459e_idx',
            old_name='prod_variant_active_idx',
        ),
        migrations.DeleteModel(
            name='FilterableAttribute',
        ),
    ]
