# Generated by Django 6.0.7 on 2026-07-27 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True, verbose_name='اسلاگ')),
                ('name', models.CharField(max_length=150, verbose_name='نام دسته\u200cبندی')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='آیکون')),
                ('color_hex', models.CharField(blank=True, default='#0B2447', max_length=7, verbose_name='رنگ کارت (Hex)')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی پروژه',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای پروژه',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='عنوان متا')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='توضیحات متا')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og/', verbose_name='تصویر Open Graph')),
                ('canonical_url', models.URLField(blank=True, verbose_name='آدرس Canonical')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True, verbose_name='اسلاگ')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده')], default='draft', max_length=10, verbose_name='وضعیت')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان پروژه')),
                ('client_name', models.CharField(blank=True, max_length=150, verbose_name='نام کارفرما')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='محل اجرا')),
                ('execution_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='سال اجرا')),
                ('short_description', models.CharField(max_length=300, verbose_name='توضیح کوتاه')),
                ('description', models.TextField(verbose_name='شرح کامل پروژه')),
                ('cover_image', models.ImageField(upload_to='projects/covers/', verbose_name='تصویر شاخص')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.projectcategory', verbose_name='دسته\u200cبندی صنعت')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
                'ordering': ['-is_featured', 'order', '-execution_year'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('image', models.ImageField(upload_to='projects/gallery/', verbose_name='تصویر')),
                ('caption', models.CharField(blank=True, max_length=150, verbose_name='عنوان تصویر')),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'تصویر پروژه',
                'verbose_name_plural': 'گالری تصاویر پروژه',
                'ordering': ['order'],
            },
        ),
    ]
