# Generated by Django 6.0.7 on 2026-07-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان مرحله')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیح')),
                ('step_number', models.PositiveIntegerField(verbose_name='شماره مرحله')),
            ],
            options={
                'verbose_name': 'مرحله فرآیند',
                'verbose_name_plural': 'مراحل فرآیند کاری',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='عنوان متا')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='توضیحات متا')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og/', verbose_name='تصویر Open Graph')),
                ('canonical_url', models.URLField(blank=True, verbose_name='آدرس Canonical')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True, verbose_name='اسلاگ')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده')], default='draft', max_length=10, verbose_name='وضعیت')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان خدمت')),
                ('short_description', models.CharField(max_length=300, verbose_name='توضیح کوتاه')),
                ('description', models.TextField(verbose_name='توضیحات کامل')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='آیکون FontAwesome')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
                'ordering': ['order'],
            },
        ),
    ]
