# Generated by Django 6.0.7 on 2026-07-27 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام\u200cهای تماس',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان شغلی')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='واحد')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='محل کار')),
                ('employment_type', models.CharField(choices=[('full_time', 'تمام\u200cوقت'), ('part_time', 'پاره\u200cوقت'), ('contract', 'پروژه\u200cای')], default='full_time', max_length=50, verbose_name='نوع همکاری')),
                ('description', models.TextField(verbose_name='شرح شغل')),
                ('requirements', models.TextField(blank=True, verbose_name='شرایط احراز')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'فرصت شغلی',
                'verbose_name_plural': 'فرصت\u200cهای شغلی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('company_name', models.CharField(blank=True, max_length=150, verbose_name='نام شرکت')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('project_type', models.CharField(blank=True, max_length=150, verbose_name='نوع پروژه')),
                ('budget_range', models.CharField(blank=True, max_length=100, verbose_name='محدوده بودجه تقریبی')),
                ('description', models.TextField(verbose_name='شرح درخواست')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='quotes/', verbose_name='فایل پیوست (نقشه/مشخصات)')),
                ('is_read', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'درخواست استعلام قیمت',
                'verbose_name_plural': 'درخواست\u200cهای استعلام قیمت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('resume', models.FileField(upload_to='careers/resumes/', verbose_name='فایل رزومه')),
                ('cover_letter', models.TextField(blank=True, verbose_name='متن معرفی')),
                ('is_reviewed', models.BooleanField(default=False)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='contact.jobposition', verbose_name='موقعیت شغلی')),
            ],
            options={
                'verbose_name': 'درخواست استخدام',
                'verbose_name_plural': 'درخواست\u200cهای استخدام',
                'ordering': ['-created_at'],
            },
        ),
    ]
