# Generated by Django 6.0.7 on 2026-10-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_site_heading_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='لینک Google Maps را وارد کنید؛ هم لینک معمولی نقشه و هم لینک Embed پشتیبانی می\u200cشود.', verbose_name='لینک نقشه گوگل'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='theme_menu_color',
            field=models.CharField(default='#0B2447', max_length=7, verbose_name='رنگ نوار منو'),
        ),
    ]
