# Generated by Django 6.0.7 on 2026-10-09 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_homepromobanner'),
        ('core', '0009_alter_sitesetting_map_embed_url_and_more'),
    ]

    operations = [
    ]
