# Generated by Django 6.0.7 on 2026-07-27 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام دسته\u200cبندی')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی گالری',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای گالری',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('media_type', models.CharField(choices=[('image', 'تصویر'), ('video', 'ویدیو')], default='image', max_length=10, verbose_name='نوع رسانه')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='عنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/images/', verbose_name='تصویر')),
                ('video_url', models.URLField(blank=True, verbose_name='لینک ویدیو (Youtube/Aparat)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gallery.gallerycategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'آیتم گالری',
                'verbose_name_plural': 'آیتم\u200cهای گالری',
                'ordering': ['order'],
            },
        ),
    ]
