# Generated by Django 6.0.7 on 2026-07-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='use_as_hero_background',
            field=models.BooleanField(default=False, help_text='این تصویر به\u200cصورت نیمه\u200cشفاف در پس\u200cزمینه بخش هیرو صفحه اصلی نمایش داده می\u200cشود. فقط یک تصویر می\u200cتواند فعال باشد.', verbose_name='استفاده به\u200cعنوان پس\u200cزمینه صفحه اصلی'),
        ),
    ]
