# Generated by Django 6.0.7 on 2026-08-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_cancel_reason_order_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_details',
            field=models.CharField(blank=True, max_length=255, verbose_name='جزئیات آدرس (پلاک، واحد، طبقه)'),
        ),
        migrations.AddField(
            model_name='order',
            name='county',
            field=models.CharField(blank=True, max_length=100, verbose_name='شهرستان'),
        ),
        migrations.AddField(
            model_name='order',
            name='province',
            field=models.CharField(blank=True, max_length=100, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='شماره همراه'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(verbose_name='آدرس دقیق پستی'),
        ),
    ]
