# Generated by Django 6.0.7 on 2026-07-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('history', models.TextField(blank=True, verbose_name='تاریخچه شرکت')),
                ('mission', models.TextField(blank=True, verbose_name='ماموریت')),
                ('vision', models.TextField(blank=True, verbose_name='چشم\u200cانداز')),
                ('approach', models.TextField(blank=True, verbose_name='رویکرد ما')),
                ('factory_intro', models.TextField(blank=True, verbose_name='معرفی کارخانه')),
                ('capabilities', models.TextField(blank=True, verbose_name='توانمندی\u200cها')),
            ],
            options={
                'verbose_name': 'محتوای درباره ما',
                'verbose_name_plural': 'محتوای درباره ما',
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.CharField(max_length=255, verbose_name='توضیح')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='آیکون')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ارزش سازمانی',
                'verbose_name_plural': 'ارزش\u200cهای سازمانی',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ManagementMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('position', models.CharField(max_length=150, verbose_name='سمت')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='management/', verbose_name='تصویر')),
                ('bio', models.TextField(blank=True, verbose_name='بیوگرافی کوتاه')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'عضو مدیریت',
                'verbose_name_plural': 'اعضای مدیریت',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='عنوان متا')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='توضیحات متا')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og/', verbose_name='تصویر Open Graph')),
                ('canonical_url', models.URLField(blank=True, verbose_name='آدرس Canonical')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True, verbose_name='اسلاگ')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('is_published', models.BooleanField(default=True)),
                ('show_in_footer', models.BooleanField(default=False, verbose_name='نمایش در فوتر')),
            ],
            options={
                'verbose_name': 'صفحه',
                'verbose_name_plural': 'صفحات',
            },
        ),
    ]
