# Generated by Django 6.0.7 on 2026-07-28 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['title'], 'verbose_name': 'صفحه', 'verbose_name_plural': 'صفحات'},
        ),
    ]
